[package]
name = "bdd-rust-multiprotocol-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

axum = { version = "0.8", features = ["ws"] }
tower = "0.4"
tower-http = { version = "0.6", features = ["trace", "cors"] }

tonic = "0.12"
prost = "0.13"

async-graphql = "7"
async-graphql-axum = "7"

quick-xml = { version = "0.36", features = ["serialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
anyhow = "1"
async-trait = "0.1"

tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
tonic-build = "0.12"

[dev-dependencies]
cucumber = "0.21"
futures-util = "0.3"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
tokio-tungstenite = "0.24"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.30.13"

[[test]]
name = "health_steps"

[[test]]
name = "rest_get_steps"

[[test]]
name = "soap_acknowledgement_steps"

[[test]]
name = "graphql_query_steps"

[[test]]
name = "grpc_hello_steps"

[[test]]
name = "fix_heartbeat_steps"

[[test]]
name = "websocket_steps"

[[test]]
name = "controlled_workload_steps"


